---
# This block contains general and global configuration which is in both modes
general:
  # token: 32 bytes of string. this will be used on agent and server side to encryption
  token: "af445adb-2434-4975-9445-2c1b2231"
  # fakeUrl: string
  # Defines the fake url between agent and server
  fakeUrl: "nipo.ciron.net"
  # method: "HEAD|GET|POST|PUT|DELETE"
  # Defines with which method
  #   you like to send requests from agent to server
  method: "GET"
  # timeout: unsigned short
  # Defines the timeout for I/O Operation in seconds. 0 indicates no timeout.
  #   Useful to automatically close stalled connections.
  timeout: 10


# This block is to define log directives
log:
  # logLevel: "INFO|TRACE|DEBUG"
  logLevel: "DEBUG"
  # logFile: "/var/log/nipo/nipo.log"
  #   Path of log file
  logFile: "/var/log/nipovpn/nipovpn.log"

# This block is to define server directives
server:
  # threads: number of threads in server
  threads: 8
  # listenIp: which must be IPv4 which is used on server
  listenIp: "127.0.0.10"
  # listenPort: the port number which will be used on server
  listenPort: 8081
  tlsEnable: false
  tlsVerifyPeer: false
  tlsCertFile: "/etc/nipovpn/server.crt"
  tlsKeyFile: "/etc/nipovpn/server.key"
  tlsCaFile: ""

# This block is to define agent directives
agent:
  # threads: number of threads in agent
  threads: 8
  # listenIp: which must be IPv4 which is used on agent
  listenIp: "0.0.0.0"
  # listenPort: the port number which will be used on agent
  listenPort: 8080
  # serverIp: IPv4 of the nipoServer
  serverIp: "127.0.0.10"
  # serverPort: port number of the nipoServer
  serverPort: 8081
  # httpVersion: This version will be used between agent and server
  httpVersion: "1.1"
  # userAgent: This is the http user agent which will be used between agent and server
  userAgent : "NipoAgent"
  tlsEnable: false
  tlsVerifyPeer: false
  tlsCaFile: ""