---
# This block contains general and global configuration which is in both modes
general:
  # token: 32 bytes of string. this will be used on agent and server side to encryption
  token: "af445adb-2434-4975-9445-2c1b2231"
  # fakeUrls:
  # Defines the list of fake urls between agent and server
  fakeUrls:
    - www.google.com
    - nipo.ciron.net
    - sudoer.net
    - sudoer.ir
  # methods:
  # Defines the list of using methods
  #   you like to send requests from agent to server
  # Program will choose randomly from this list
  methods:
    - HEAD
    - GET
    - POST
    - PUT
    - DELETE
  # endPoints:
  # Defines the list of using endpoints
  #   you like to send requests from agent to server
  # Program will choose randomly from this list
  endPoints:
    - api
    - login
    - user
    - update
  # timeout: unsigned short
  # Defines the timeout for I/O Operation in seconds. 0 indicates no timeout.
  #   Useful to automatically close stalled connections.
  timeout: 10
  # tunnelEnable: bool
  # Defines the connection mode between agent and server. If enabled then the traffic
  #   will be TCP/TLS tunnel like.
  tunnelEnable: false
  # connectionReuse: bool
  # If false then it will use same connection between agent and server to handle client request
  #   If true then it will create new connection for each request between agent and server
  connectionReuse: true
  # tlsEnable: bool
  # It enables or disables tls between agent and server
  tlsEnable: false
  # tlsVerifyPeer: bool
  # Use it to controll if the certificate should be validated or not
  tlsVerifyPeer: false
  # Use following configurations to specify the key and cert which will be used between agent and server
  tlsCertFile: "/etc/nipovpn/server.crt"
  tlsKeyFile: "/etc/nipovpn/server.key"
  tlsCaFile: ""


# This block is to define log directives
log:
  # logLevel: "INFO|TRACE|DEBUG"
  logLevel: "DEBUG"
  # logFile: "/var/log/nipo/nipo.log"
  #   Path of log file
  logFile: "/var/log/nipovpn/nipovpn.log"

# This block is to define server directives
server:
  # threads: number of threads in server
  threads: 8
  # listenIp: which must be IPv4 which is used on server
  listenIp: "0.0.0.0"
  # listenPort: the port number which will be used on server
  listenPort: 80


# This block is to define agent directives
agent:
  # threads: number of threads in agent
  threads: 8
  # listenIp: which must be IPv4 which is used on agent
  listenIp: "0.0.0.0"
  # listenPort: the port number which will be used on agent
  listenPort: 8080
  # serverIp: IPv4 of the nipoServer
  serverIp: "127.0.0.10"
  # serverPort: port number of the nipoServer
  serverPort: 80
  # httpVersion: This version will be used between agent and server
  httpVersion: "1.1"
  # userAgent: This is the http user agent which will be used between agent and server
  userAgent : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0"
