---
# This block contains general and global configuration which is in both modes
general:
  # token: 32 bytes of string. this will be used on agent and server side to encryption
  token: "af445adb-2434-4975-9445-2c1b2231"
  # fakeUrl: string
  # Defines the fake url and endpoint between agent and server
  fakeUrl: "http://www.adas.com/api01"
  # method: "HEAD|GET|POST|PUT|DELETE"
  # Defines with which method
  #   you like to send requests from agent to server
  method: "POST"
  # timeWait: unsigned int(0-4,294,967,295)
  # Defines the time wait between each repeat to read from socket.
  #   This directive will be useful when you expect to read very long stream from socket
  timeWait: 0
  # timeout: unsigned short
  # Defines the timeout for I/O Operation in seconds. 0 indicates no timeout.
  #   Useful to automatically close stalled connections.
  timeout: 10
  # repeatWait: unsigned short(1-65,635)
  # Defines the loop count which will try to repeat read from socket.
  #   Same as timeWait
  repeatWait: 1
  # chunkHeader: String
  # Defines the chunk header that you want to inform Agent/Server if it is end or not.
  chunkHeader: "END"
  # chunkSize: unsigned short(512-65,535)
  # Defines the chunk size that you want to read from socket.
  chunkSize: 8152

# This block is to define log directives
log:
  # logLevel: "INFO|TRACE|DEBUG"
  logLevel: "TRACE"
  # logFile: "/var/log/nipo/nipo.log"
  #   Path of log file
  logFile: "/var/log/nipovpn/nipovpn.log"

# This block is to define server directives
server:
  # threads: number of threads in server
  threads: 8
  # listenIp: which must be IPv4 which is used on server
  listenIp: "0.0.0.0"
  # listenPort: the port number which will be used on server
  listenPort: 443

# This block is to define agent directives
agent:
  # threads: number of threads in agent
  threads: 8
  # listenIp: which must be IPv4 which is used on agent
  listenIp: "0.0.0.0"
  # listenPort: the port number which will be used on agent
  listenPort: 8080
  # serverIp: IPv4 of the nipoServer
  serverIp: "127.0.0.1"
  # serverPort: port number of the nipoServer
  serverPort: 443
  # httpVersion: This version will be used between agent and server
  httpVersion: "1.1"
  # userAgent: This is the http user agent which will be used between agent and server
  userAgent : "NipoAgent"
