---
general:
  delimiter: ''
  fakeUrl: "http://www.adas.com/api01"
  method: "GET"
  timeWait: 1
  repeatWait: 5

log:
  logLevel: "INFO"
  logFile: "/var/log/nipo/nipo.log"

server:
  threads: 4
  listenIp: "127.0.0.50"
  listenPort: 443
  webDir: "/var/lib/niposerver"
  sslKey: "/etc/niposerver/ssl.key"
  sslCert: "/etc/niposerver/ssl.cert"

agent:
  threads: 4
  listenIp: "127.0.0.10"
  listenPort: 8080
  serverIp: "127.0.0.50"
  serverPort: 443
  encryption: "no"
  token: "af445adb-2434-4975-9445-2c1b223d556e"
  httpVersion: "1.1"
  userAgent : "NipoAgent
