---
# This block contains general and global configucration which is in both modes
general:
  fakeUrl: "http://www.adas.com/api01"
  # method: "HEAD|GET|POST|PUT|DELETE"
  # Defines with which method
  #   you like to send requests from agent to server
  method: "HEAD"
  # timeWait: unsigned int(0-4,294,967,295)
  # Defines the time wait between each reapeat to read from socket.
  #   This directive will be usefull when you expect to read very long stream from socket
  timeWait: 0
  # repeatWait: unsigned short(1-65,635)
  # Defines the loop count which will try to repeat read from socket.
  #   Same as timeWait
  repeatWait: 1
  keepAlive: 5

# This block is to define log directives
log:
  # logLevel: "INFO|TRACE|DEBUG"
  logLevel: "DEBUG"
  # logFile: "/var/log/nipo/nipo.log"
  #   Path of log file
  logFile: "/var/log/nipo/nipo.log"

# This block is to define server directives
server:
  # threads: number of threads in server
  threads: 4
  listenIp: "127.0.0.50"
  listenPort: 443
  webDir: "/var/lib/niposerver"
  sslKey: "/etc/niposerver/ssl.key"
  sslCert: "/etc/niposerver/ssl.cert"

# This block is to define agent directives
agent:
  threads: 4
  listenIp: "127.0.0.10"
  listenPort: 8080
  serverIp: "127.0.0.50"
  serverPort: 443
  encryption: "no"
  token: "af445adb-2434-4975-9445-2c1b223d556e"
  httpVersion: "1.1"
  userAgent : "NipoAgent
