name: Build and Release Debian Package

on:
  push:
    branches:
      - main
    paths:
      - 'core/src/**'
      - '.github/workflows/debian-dev.yml'
      - 'nipovpn/**'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set package version
        run: echo "PACKAGE_VERSION=0.1.${{ github.run_number }}" >> "$GITHUB_ENV"

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev \
            build-essential \
            lintian \
            fakeroot \
            devscripts \
            cmake \
            libssl-dev \
            libboost-all-dev \
            libyaml-cpp-dev

      - name: Build the package
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
          cd ..

          rm -rf package
          mkdir -p package/DEBIAN
          mkdir -p package/usr/bin

          cp build/core/nipovpn package/usr/bin/nipovpn
          chmod 755 package/usr/bin/nipovpn

          cat > package/DEBIAN/control <<EOF
          Package: nipovpn
          Version: ${PACKAGE_VERSION}
          Maintainer: Morteza Bashsiz
          Architecture: amd64
          Description: Powerful and Secure HTTP/S Proxy
          Depends: libyaml-cpp0.8
          Homepage: https://github.com/MortezaBashsiz/nipovpn
          EOF

          dpkg-deb --build package "build/nipovpn_dev_${PACKAGE_VERSION}_amd64.deb"

      - name: Show package information
        run: |
          dpkg -I "build/nipovpn_dev_${PACKAGE_VERSION}_amd64.deb"

      - name: Upload Debian package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nipovpn
          path: build/nipovpn_dev_${{ env.PACKAGE_VERSION }}_amd64.deb

  release:
    needs: build
    runs-on: ubuntu-latest
  
    permissions:
      contents: write
  
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: nipovpn
          path: ./
  
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: Version v${{ env.PACKAGE_VERSION }}
          files: nipovpn_dev_${{ env.PACKAGE_VERSION }}_amd64.deb
        env:
          GITHUB_TOKEN: ${{ github.token }}