name: Build and Release Debian Package - MAIN

on:
  push:
    branches:
      - main
    paths:
      - 'core/src/**'
      - '.github/workflows/debian.yml'
      - 'nipovpn/**'

permissions:
  contents: write

env:
  PACKAGE_VERSION: 1.1.${{ github.run_number }}
  PACKAGE_FILE: nipovpn_1.1.${{ github.run_number }}_amd64.deb

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev build-essential lintian fakeroot devscripts cmake \
            libssl-dev libboost-all-dev libyaml-cpp-dev

      - name: Build the package
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
          cd ..

          rm -rf package
          mkdir -p package/DEBIAN package/usr/bin

          cp build/core/nipovpn package/usr/bin/nipovpn
          chmod 755 package/usr/bin/nipovpn

          cat > package/DEBIAN/control <<'EOF'
Package: nipovpn
Version: PLACEHOLDER_VERSION
Maintainer: Morteza Bashsiz
Architecture: amd64
Description: Powerful and Secure HTTP/S Proxy
Depends: libyaml-cpp0.8
Homepage: https://github.com/MortezaBashsiz/nipovpn
EOF
          sed -i "s/PLACEHOLDER_VERSION/${PACKAGE_VERSION}/" package/DEBIAN/control
          dpkg-deb --build package "build/${PACKAGE_FILE}"

      - name: Show package information
        run: |
          dpkg -I "build/${PACKAGE_FILE}"
          ls -lah build/

      - name: Upload Debian package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nipovpn-main-deb
          path: build/${{ env.PACKAGE_FILE }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: nipovpn-main-deb
          path: ./

      - name: Check downloaded files
        run: |
          ls -lah

      - name: Create GitHub MAIN Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: Version v${{ env.PACKAGE_VERSION }}
          prerelease: false
          files: ${{ env.PACKAGE_FILE }}
        env:
          GITHUB_TOKEN: ${{ github.token }}