name: build debian

on:
  push:
    branches: [ "morteza/debian" ]
    # paths:
    # - 'core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build-deb-action
        uses: jiro4989/build-deb-action@v3.1.0
        with:
          package_root: ./nipovpn
            
